---
title: "Harmonization"
output:
  rmarkdown::github_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
    code_folding: show
    theme: flatly
    highlight: tango
---

Code for harmonizing multiple genotyped/WGS cohorts into a single dataset.
Liftover to a common build, per-cohort and merged QC, PCA, ADMIXTURE, Fst between clusters, and annotation of clinically relevant SNPs.

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE, engine = "bash")
```

# Data preparation

## Liftover

Convert each input cohort's PLINK files to VCF, liftover from hg18/hg19 to hg38, then
convert back to PLINK, appending each lifted cohort's path to a running list.

```{bash liftover}
# This code performs LiftOver on a list of plink files provided in a $list
# the final file names are written in the file $cohort

#specify hg18 or hg19
hg=18
#plink file names
list=~/midProject/data/reference/cohorts/hg${hg}cohorts.txt
cohort=~/midProject/data/reference/cohorts/harmonization/allcohorts.txt
plink2=/path/to/plink2
# Iteration
while read plink_file; do
[[ -z "$plink_file" || "$plink_file" =~ ^# ]] && continue
echo "Processing: $plink_file"

name=$(basename "$plink_file");
path=$(dirname "$plink_file");  
fasta=/path/to/reference_genomes/b38/Homo_sapiens_assembly38.fasta; 
fasta19=/path/to/reference_genomes/hg19/hg19.fa;
chain=/path/to/genetic_maps/liftover/hg${hg}ToHg38.over.chain.gz; 
vcf=$plink_file.vcf; 
chr=~/midProject/data/reference/cohorts/chr_name_conv.txt; 

# (1) convert to VCF
$plink2 \
--bfile $plink_file --snps-only 'just-acgt' --recode vcf --out $plink_file; 

# add chr notation to match the chain file
bcftools annotate --rename-chrs $chr -Oz -o $vcf.gz --write-index $vcf
#rm $vcf

# (2) LiftOver
java -jar /path/to/picard/picard_v3.1.1.jar \
LiftoverVcf --CHAIN $chain \
--INPUT $vcf.gz \
--OUTPUT ${path}/hg38_${name}.vcf.gz \
--REFERENCE_SEQUENCE $fasta \
--RECOVER_SWAPPED_REF_ALT \
--REJECT ${path}/unlifted_${name}.vcf \
--WARN_ON_MISSING_CONTIG \
--DISABLE_SORT; 

# (3) Convert to plink
$plink2 \
--vcf ${path}/hg38_${name}.vcf.gz \
--keep-allele-order \
--set-all-var-ids chr@:#:\$r:\$a --sort-vars \
--make-pgen --allow-extra-chr --chr 1-22 \
--snps-only 'just-acgt' -max-alleles 2 \
--out ${path}/hg38_${name};

# fix ID after conversion from VCF
less ${path}/${name}.fam | awk -v OFS="\t" '{print "0", $1"_"$2, $1, $2}' > ${path}/id_${name}.txt
$plink2 \
--pfile ${path}/hg38_$name \
--keep-allele-order \
--update-ids ${path}/id_${name}.txt --make-bed --out ${path}/hg38_$name; 

# add file to cohort list
echo ${path}/hg38_${name} >> $cohort; 
wc -l ${path}/hg38_${name}.bim
wc -l ${path}/hg38_${name}.fam

# delete unnecessary files
rm $vcf*
rm ${path}/hg38_${name}.p*

done < $list
```

## QC

### Individual QC

Per-cohort QC: exclude non-biallelic/duplicate variants, low call-rate variants and
samples, rare MAF, and HWE outliers.

```{bash individual-qc}
plink2=/path/to/plink2
cohort=~/midProject/data/reference/cohorts/harmonization/allcohorts

while read file; do

$plink2 \
-bfile ${file} \
--keep-allele-order \
-max-alleles 2 --geno 0.1 \
--rm-dup force-first \
--make-bed --out ${file}qc;
wc -l ${file}qc.bim >> counts_allcohorts.txt;
wc -l ${file}qc.fam >> counts_allcohorts.txt;

$plink2 \
-bfile ${file}qc \
--keep-allele-order \
--mind 0.1 \
--make-bed --out ${file}qc;
wc -l ${file}qc.bim >> counts_allcohorts.txt;
wc -l ${file}qc.fam >> counts_allcohorts.txt;

$plink2 \
-bfile ${file}qc \
--keep-allele-order \
--maf 0.01 \
--max-maf 0.99 \
--make-bed --out ${file}qc;
wc -l ${file}qc.bim >> counts_allcohorts.txt;
wc -l ${file}qc.fam >> counts_allcohorts.txt;

$plink2 \
-bfile ${file}qc \
--keep-allele-order \
--hwe 1e-6  \
--make-bed --out ${file}qc;
wc -l ${file}qc.bim >> counts_allcohorts.txt;
wc -l ${file}qc.fam >> counts_allcohorts.txt;

$plink2 \
-bfile ${file}qc \
--keep-allele-order \
--write-snplist \
--out ${file}qc;

done < ${cohort}.txt
```

## Merge

Merge the per-cohort QC'd PLINK files into one dataset, then sort variants.

```{bash merge}
plink=/path/to/plink_v1.9/plink
plink2=/path/to/plink2
cohort=~/midProject/data/reference/cohorts/harmonization/allcohorts

> ${cohort}_mergelist.txt
while read file; do
[[ "$file" =~ ^# ]] && continue
echo ${file}qc >> ${cohort}_mergelist.txt; #will merge the QCed files
done < ${cohort}.txt

#merge
$plink \
--merge-list ${cohort}_mergelist.txt --make-bed --out ${cohort}

#exclude missnp (if number of SNPs is not too large < 500, otherwise try --flip)
#while read file; do
#$plink \
#--bfile ${file} --exclude ${cohort}-merge.missnp --make-bed --out ${file}; done < ${cohort}_mergelist.txt
# then merge again

#sort file
$plink2 \
--bfile ${cohort} --sort-vars \
--keep-allele-order \
--make-pgen --out ${cohort}

$plink2 \
--pfile ${cohort} \
--keep-allele-order \
--make-bed --out ${cohort}

wc -l ${cohort}.fam
#4,313 samples
wc -l ${cohort}.bim
#14,323,944 snps
```

### Merged QC

QC on the merged dataset (higher thresholds than individual QC, since per-cohort QC
was already applied), exclude the MHC region, and remove related individuals.

```{bash merged-qc}
## For joined cohort
# --mind and --geno default is 0.1
# used higher values as QC has already been performed individually and the number of merged studies is large 

cd ~/midProject/data/reference/cohorts/harmonization
plink=/path/to/plink_v1.9/plink
plink2=/path/to/plink2
cohort=~/midProject/data/reference/cohorts/harmonization/allcohorts

# exclude SNPs with low call rate
$plink2 \
--bfile ${cohort} --geno 0.3 \
--keep-allele-order \
--make-bed --out ${cohort}qc

# exclude samples with low call rate
$plink2 \
--bfile ${cohort}qc --mind 0.99 \
--keep-allele-order \
--make-bed --out ${cohort}qc

# Exclude MHC regions
awk -F'\t' '$1 == 6 {split($2, pos, ":"); if (pos[2] >= 28510120 && pos[2] <= 33480577) print}' ${cohort}qc.bim | cut -f 2 > ${cohort}.mhc
$plink2 \
--bfile ${cohort}qc --exclude ${cohort}.mhc --keep-allele-order --make-bed --out ${cohort}qc

# prune related individuals
$plink2 --bfile ${cohort}qc \
  --keep-allele-order \
  --king-cutoff 0.177 \
  --out ${cohort}qc

$plink2 --bfile ${cohort}qc \
  --keep-allele-order \
  --remove ${cohort}qc.king.cutoff.out.id \
  --make-bed --out ${cohort}qc_unrel;
  
#list of populations 
less ${cohort}.fam | cut -f 1 | sed "s/_/\t/g" | cut -f 1 | sed 's/|/\t/g' | sed "s/]/\t/g" | awk '{print $NF}' | sort -u > countries.txt
```

### Get MID targeted cohort

Subset the merged cohort down to a target set of countries/populations included in at least one MID definition.

```{bash target-definition}
#get definitions
plink2=/path/to/plink2
cohort=~/midProject/data/reference/cohorts/harmonization/allcohortsqc
targetcohort=~/midProject/data/reference/cohorts/harmonization/targetcohort

grep -Ff target_countries.txt ${cohort}.fam > targetids.txt

$plink2 \
--bfile ${cohort} --keep targetids.txt --make-bed --out $targetcohort

$plink2 \
--bfile ${targetcohort} --remove ${targetcohort}_outliers.txt --make-bed --out ${targetcohort}
```

### Select random/exclude outliers

To keep population/country groups from dominating downstream analyses (PCA, ADMIXTURE),
downsample large groups: cap each broad region at 200 samples, sampling proportionally
across countries within it.

**selectrandom.py**
```{python select-random}
import pandas as pd
import sys

# Read the input CSV file
df = pd.read_csv(sys.argv[1], header=None, names=['FamilyID', 'SampleID'], usecols=[0, 1], sep=' ')

# Extract the 'country' from 'FamilyID'
df['cont'] = df['FamilyID'].apply(lambda x: x.split('_')[-1])
df['country'] = df['FamilyID'].apply(lambda x: x.split(']')[-1].split('|')[-1].split('_')[0])

random_sample = pd.DataFrame()
regions = df['cont'].unique()

# Sample
for cont in regions:
    print(cont)
    cont_df = df[df['cont'] == cont]
    n = cont_df.shape[0]
    print(n)
    if n > 200:
        f = 200/n
        sample = cont_df.groupby('country', group_keys=False).apply(lambda x: x.sample(frac=f))
    else:
        sample = cont_df
    random_sample = pd.concat([random_sample, sample[['FamilyID', 'SampleID']]], ignore_index=True)

# Save
filename = sys.argv[1] + "_random.csv"
random_sample.to_csv(filename, index=False, header=False, sep = "\t")
```

Run the downsampling script, extract the resulting random sample from the unrelated
merged cohort, and exclude any PCA-flagged outliers from both the random subset and
the full QC'd cohort.

```{bash equal_pops}
# generate random sample
cohort=~/midProject/data/reference/cohorts/harmonization/allcohorts
plink2=/path/to/plink2

python ~/midProject/scripts/preprocessing/subset/selectrandom.py ${cohort}qc_unrel.fam

# extract random samples and QC
$plink2 \
--bfile ${cohort}qc_unrel --keep ${cohort}qc_unrel.fam_random.csv --make-bed --out ${cohort}_random

#exclude outliers (determined by pca)
$plink2 \
--bfile ${cohort}_random --remove ${cohort}_random_outliers.txt --make-bed --out ${cohort}_random

$plink2 \
--bfile ${cohort}qc --remove ${cohort}_random_outliers.txt --make-bed --out ${cohort}qc
#4179 samples
```

# PCA

## Generate PCs using Plink

Run PCA on both the target cohort and
the full harmonized cohort.

```{bash pca}
#pca
cd ~/midProject/results/raw_outputs/pca

plink=/path/to/plink2
cohorts=(
    ~/midProject/data/reference/cohorts/harmonization/targetcohort
    ~/midProject/data/reference/cohorts/harmonization/allcohorts
)

for cohort in "${cohorts[@]}"; do
name=$(echo "$cohort" | sed 's:.*/::')
output=~/midProject/results/raw_outputs/pca/${name}
pcs=10

$plink \
--bfile $cohort \
--keep-allele-order \
--freq \
--pca ${pcs} \
--out $output; done
```

# ADMIXTURE

## Perform ADMIXTURE

```{bash run-admixture}
admixture=/path/to/admixture_linux-1.3.0/admixture
cohort=~/midProject/data/reference/cohorts/harmonization/allcohorts_random

$admixture --cv ${cohort}.bed ${SLURM_ARRAY_TASK_ID};
```

Extract the cross-validation error for each K from the job logs.

```{bash admixture-cv-error}
cat admixture-job* | grep "CV error (K=" | sed "s/CV error (K=//g" | sed "s/): /\t/g" | sort -V > ../allcohorts_random_kerror.tsv
```

# Fst

## Fst between k clusters

Compute Fst between the K clusters identified from PCA (clusters generated
by `Fig02_neighboring_pca_admix.R`).

```{bash fst}
cohort=~/midProject/data/reference/cohorts/harmonization/allcohorts_random
plink=/path/to/plink2
samples=~/midProject/results/raw_outputs/pca/allcohorts_random.clusters.tsv
output=~/midProject/results/raw_outputs/fst/allcohorts_random.clusters

# this should be equal
wc -l $samples
wc -l ${cohort}.fam


# Get high QC file for Fst
$plink --bfile ${cohort} \
--geno 0.1 \
--make-bed -out ${cohort}_strictqc

#Fst
$plink --bfile ${cohort}_strictqc \
-within $samples \
-double-id -fst CATPHENO method=hudson \
-out ${output}
```

# Distribution of clinically relevant SNPs

## ClinPGx annotation

Download and reformat the ClinPGx variant annotation set (mapping RefSeq accessions to
chromosome names), then intersect it with the strictly-QC'd cohort's variant list.

```{bash clinpgx-download}

# Download summary annotation
wget https://api.clinpgx.org/v1/download/file/data/variants.zip
unzip variants.zip

# convert Ref Seq to CHROM
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.40_GRCh38.p14/GCF_000001405.40_GRCh38.p14_assembly_report.txt
less variants.tsv | cut -f 5 | grep -v Location | sed "s/:/\t/g" | cut -f 1 | sort -u | grep -v ^$ > ref_seq_chrom.txt
cat GCF_000001405.40_GRCh38.p14_assembly_report.txt | grep -Fwf ref_seq_chrom.txt | cut -f 7,10 > map.txt 
sed -i 's/\r$//' map.txt

#Format variants file
less variants.tsv | cut -f 1,5,11 > tmp
awk 'match($0, /[ACGT]>[ACGT]/) { print $2, substr($0, RSTART, RLENGTH), $1 }' tmp | sed "s/:/\t/g" | sed "s/ /\t/g" | sed "s/>/\t/g" > tmp1


awk 'NR==FNR { map[$1]=$2; next } { $1 = map[$1]; print }' map.txt tmp1 | sed "s/ /\t/g" > clinpgx_variants_20260205.tsv
rm tmp*

## Annotate SNPs with ClinPGx
## apply strict QC
name=allcohorts_random_strictqc
bed=~/midProject/data/reference/cohorts/harmonization/${name}.bim
annotation=~/midProject/data/reference/annotations/clinpgx/clinpgx_variants_20260205.tsv

less $bed | cut -f 2 | sed "s/:/\t/g" > ${name}.snps.tsv

grep -Ff ${name}.snps.tsv $annotation > ${name}_clinpgx.intersect.txt
```

Compute allele frequencies stratified by region, then
intersect the region frequency tables with the ClinPGx
variant annotations.

```{bash clinpgx-frequencies}
## Step 2: Get allele frequency per region
# AF per regions
regions=~/midProject/results/raw_outputs/pca/allcohorts_random.regions.tsv
name=allcohorts_regions
head -n 1 $clusters | sed "s/Cluster/Region/g" > $regions
less $clusters | grep -v ^# | cut -f 1 | sed "s/_/\t/g" | cut -f 2 > tmp
less $clusters | grep -v ^# | cut -f 1,2 > tmp1
paste tmp1 tmp >> $regions

$plink \
--bfile $cohort \
--within $regions \
--freq --out $name

# intersect with annotations in R
clinpgx=~/midProject/data/reference/annotations/clinpgx/allcohorts_random_strictqc_clinpgx.intersect.txt
gwas=~/midProject/data/reference/annotations/gwas_catalog/allcohorts_random_strictqc_gwas_catalog.intersect.txt
regions=allcohorts_regions.frq.strat

#use clinical_snp_distribution.R
```
